### ISSUE TITLE
Question: How to best handle redirect URIs in query params?

### ISSUE THREAD

**Issue by mherodev** [markau/express-sanitizer#5]
I'm running into an issue where sanitizer is breaking redirect URLs; what's the best way to handle a URL in a query param (e.g. `www.mysite.com/?redirect=/my/ampersands/get/replaced`) that's getting encoded from `www.redirectExample.com/?ampersands=get&converted=to` to `www.redirectExample.com/?ampersands=get&amp;converted=to`?

Our best thought for a generic solution is to regex for url query params and do a simple find-replace on `&amp;` but I dunno if there's a cleaner way to go.

**Comment by markau** [comment]
Hi @mherodev, sorry for the delay. I can't say I have experienced this issue, but I agree with your approach; rewrite the URL on the way in and out. Good luck.
