### ISSUE TITLE
Is it possible to whitelist particular characters from being escaped?

### ISSUE THREAD

**Issue by reubenrjs** [markau/express-sanitizer#8]
Hello,

Is it possible to whitelist specific characters from being escaped e.g. prevent "&" from being escaped to "&amp;"?

Thanks

**Comment by markau** [comment]
Hi. The base library can be passed an options object, so something like this maybe possible. Feel free to investigate and submit a PR. Having said that, your question, and my subsequent review of the base library (and it's warning "I don't have time to maintain this repo, and have long forgotten how any of it works"), has made me reflect on this project and I think it is time that it was deprecated. There is likely a better option out there so I will look into that.
